name: JesseMogle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f22'
    - '#cfad8d'
    - '#9c6f3f'
    - '#9c3e1c'
    - '#3d332a'
  brandStrength: 0.25
  lightness: 0.11457100184634328
  saturation: 0.7422394689638168
  rhythmicContrast: 0.49749331269413233
purpose: []
