name: JesseMogle
favicon: null
layout_spectrum: 0.74642
typography_spectrum: 0.53124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f22'
    - '#cfad8d'
    - '#9c6f3f'
    - '#9c3e1c'
    - '#3d332a'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
